[package]
name = "hll-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
hyperloglogplus = "0.4.1"
num-format = "0.4.4"

[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"